name: PRs and Branches

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - main
      - master
      - development

jobs:
  #############################################
  # Tests First baby! We fail, no build :(
  #############################################
  tests:
    uses: ./.github/workflows/tests.yml

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set Up CommandBox
        uses: Ortus-Solutions/setup-commandbox@v2.0.1

      - name: Install CFFormat
        run: box install commandbox-cfformat

      - name: Run CFFormat
        run: box run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Apply cfformat changes