name: Test Suites

# We are a reusable Workflow only
on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        cfengine: [ "lucee@5", "lucee@6", "adobe@2023", "adobe@2025" ]
        coldbox: [ "coldbox@7", "coldbox@be" ]
        experimental: [ false ]
        include:
            - cfengine: "boxlang@1"
              coldbox: "coldbox@be"
              experimental: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set Up CommandBox
        uses: Ortus-Solutions/setup-commandbox@v2.0.1

      - name: Install dependencies
        run: |
          box install
          box install ${{ matrix.coldbox }} --noSave

      - name: BoxLang Modules
        if: matrix.cfengine == 'boxlang@1'
        run: box server set scripts.onServerInitialInstall="install bx-compat-cfml,bx-esapi --noSave"

      - name: Start server
        run: box server start cfengine=${{ matrix.cfengine }} --noSaveSettings

      - name: Run TestBox Tests
        run: box testbox run